version: '3.2'
volumes:
  data-volume: {}
services:
  db:
    image: "mysql:5.7"
    command: --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fenix391**
      MYSQL_DATABASE: meuprimeirodb 
    ports:
      - 33061:3306  
    volumes:
       - data-volume:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
